const Rdata = [
    {
        Srno: "1",
        Name: "Raghvendra Singh",
        Address: "Maninagar, Ahmedabad",
        Phone: "9574547152, 9106071308",
        Email: "Raghav26897@Gmail.com",
        ClothesFor: "Adults",
        ClothesType: "Winter Wear",
        NoOfClothes:"25",
        
    },
    {
        Srno: "2",
        Name: "Prashant Bangad",
        Address: "Ranip, Ahmedabad",
        Phone: "9574547152, 9106071308",
        Email: "Prashant12@Gmail.com",
        ClothesFor: "Kids",
        ClothesType: "Summer Wear",
        NoOfClothes:"12",
    },
    {
        Srno: "3",
        Name: "Ansh Verma",
        Address: "Vastra, Ahmedabad",
        Phone: "9106071308",
        Email: "Anshverma@Gmail.com",
        ClothesFor: "Adults",
        ClothesType: "Winter Wear",
        NoOfClothes:"5",
    },
    {
        Srno: "4",
        Name: "Tanuj Dey",
        Address: "Maninagar, Ahmedabad",
        Phone: "9574547152",
        Email: "TanujDey@Gmail.com",
        ClothesFor: "Kids",
        ClothesType: "Winter Wear",
        NoOfClothes:"6",
    },
    {
        Srno: "5",
        Name: "Khyati Shah",
        Address: "Maninagar, Ahmedabad",
        Phone: "8596745412",
        Email: "KhyatiShah@Gmail.com",
        ClothesFor: "Kids",
        ClothesType: "Summer Wear",
        NoOfClothes:"20",
    },
    {
        Srno: "6",
        Name: "Raghav Singh",
        Address: "Maninagar, Ahmedabad",
        Phone: "9674852365",
        Email: "Raghav@Gmail.com",
        ClothesFor: "Adults",
        ClothesType: "Winter Wear",
        NoOfClothes:"12",
    },
    {
        Srno: "7",
        Name: "Devansh Parman",
        Address: "Bodakdev, Ahmedabad",
        Phone: "7489657452",
        Email: "Raghav26897@Gmail.com",
        ClothesFor: "Adults",
        ClothesType: "Summer Wear",
        NoOfClothes:"34",
    },
    {
        Srno: "8",
        Name: "Zeel Chauhan",
        Address: "Ranip, Ahmedabad",
        Phone: "8965741256",
        Email: "Zeel7@Gmail.com",
        ClothesFor: "Kids",
        ClothesType: "Winter Wear",
        NoOfClothes:"10",
    },
    {
        Srno: "9",
        Name: "Hemmu Verma",
        Address: "University, Ahmedabad",
        Phone: "8745693547",
        Email: "Hemmu@Gmail.com",
        ClothesFor: "Adults",
        ClothesType: "Winter Wear",
        NoOfClothes:"5",
    },
    {
        Srno: "10",
        Name: "Abhishek Simp",
        Address: "Bapunagar, Ahmedabad",
        Phone: "8965745126",
        Email: "Abhishek@Gmail.com",
        ClothesFor: "Adults",
        ClothesType: "Summer Wear",
        NoOfClothes:"30",
    },
];

export default Rdata;