const Rdata = [
    {
        Srno: "1",
        Name: "Raghvendra Singh",
        Address: "Maninagar, Ahmedabad",
        Phone: "9574547152, 9106071308",
        Gender:"Male",
        Email: "Raghav26897@Gmail.com",
        DOB: "26-08-1998",
        bloodgroup: "O+",
        preference:"Only in Emergency",
        
    },
    {
        Srno: "2",
        Name: "Prashant Bangad",
        Address: "Ranip, Ahmedabad",
        Phone: "9574547152, 9106071308",
        Gender:"Male",
        Email: "Prashant12@Gmail.com",
        DOB: "26-08-1998",
        bloodgroup: "O+",
        preference:"Only in Emergency",
    },
    {
        Srno: "3",
        Name: "Ansh Verma",
        Address: "Vastra, Ahmedabad",
        Phone: "9106071308",
        Email: "Anshverma@Gmail.com",
        Gender:"Male",
        DOB: "26-08-1998",
        bloodgroup: "B+",
        preference:"Only in Emergency",
    },
    {
        Srno: "4",
        Name: "Tanuj Dey",
        Address: "Maninagar, Ahmedabad",
        Phone: "9574547152",
        Email: "TanujDey@Gmail.com",
        Gender:"Male",
        DOB: "20-08-2000",
        bloodgroup: "O-",
        preference:"Only in Emergency",
    },
    {
        Srno: "5",
        Name: "Khyati Shah",
        Address: "Maninagar, Ahmedabad",
        Phone: "8596745412",
        Email: "KhyatiShah@Gmail.com",
        Gender:"Female",
        DOB: "04-03-2000",
        bloodgroup: "Ab+",
        preference:"Only in Emergency",
    },
    {
        Srno: "6",
        Name: "Raghav Singh",
        Address: "Maninagar, Ahmedabad",
        Phone: "9674852365",
        Email: "Raghav@Gmail.com",
        Gender:"Male",
        DOB: "26-08-1998",
        bloodgroup: "O+",
        preference:"Only in Emergency",
    },
    {
        Srno: "7",
        Name: "Devansh Parman",
        Address: "Bodakdev, Ahmedabad",
        Phone: "7489657452",
        Email: "Raghav26897@Gmail.com",
        Gender:"Male",
        DOB: "26-08-1998",
        bloodgroup: "O+",
        preference:"Only in Emergency",
    },
    {
        Srno: "8",
        Name: "Zeel Chauhan",
        Address: "Ranip, Ahmedabad",
        Phone: "8965741256",
        Email: "Zeel7@Gmail.com",
        Gender:"Male",
        DOB: "26-08-1998",
        bloodgroup: "AB+",
        preference:"Only in Emergency",
    },
    {
        Srno: "9",
        Name: "Hemmu Verma",
        Address: "University, Ahmedabad",
        Phone: "8745693547",
        Email: "Hemmu@Gmail.com",
        Gender:"Male",
        DOB: "26-08-1998",
        bloodgroup: "A-",
        preference:"Only in Emergency",
    },
    {
        Srno: "10",
        Name: "Abhishek Simp",
        Address: "Bapunagar, Ahmedabad",
        Phone: "8965745126",
        Email: "Abhishek@Gmail.com",
        Gender:"Male",
        DOB: "26-08-1998",
        bloodgroup: "AB+",
        preference:"Only in Emergency",
    },
];

export default Rdata;