const Rdata = [
    {
        Srno: "1",
        Name: "Raghvendra Singh",
        Address: "Maninagar, Ahmedabad",
        Phone: "9574547152, 9106071308",
        Email: "Raghav26897@Gmail.com",
        Booksfor: "Adult",
        BooksType: "Fiction",
        Noofbooks:"5",
        // Preference: "Only in Emergency"
    },
    {
        Srno: "2",
        Name: "Prashant Bangad",
        Address: "Ranip, Ahmedabad",
        Phone: "9574547152, 9106071308",
        Email: "Prashant12@Gmail.com",
        Booksfor: "Adult",
        BooksType: "Business",
        Noofbooks:"7",
    },
    {
        Srno: "3",
        Name: "Ansh Verma",
        Address: "Vastra, Ahmedabad",
        Phone: "9106071308",
        Email: "Anshverma@Gmail.com",
        Booksfor: "Adult",
        BooksType: "Comptetive Exams",
        Noofbooks:"3",
    },
    {
        Srno: "4",
        Name: "Tanuj Dey",
        Address: "Maninagar, Ahmedabad",
        Phone: "9574547152",
        Email: "TanujDey@Gmail.com",
        Booksfor: "Kids",
        BooksType: "Academics",
        Noofbooks:"5",
    },
    {
        Srno: "5",
        Name: "Khyati Shah",
        Address: "Maninagar, Ahmedabad",
        Phone: "8596745412",
        Email: "KhyatiShah@Gmail.com",
        Booksfor: "Adult",
        BooksType: "Fiction",
        Noofbooks:"5",
    },
    {
        Srno: "6",
        Name: "Raghav Singh",
        Address: "Maninagar, Ahmedabad",
        Phone: "9674852365",
        Email: "Raghav@Gmail.com",
        Booksfor: "Adult",
        BooksType: "Adventure",
        Noofbooks:"3",
    },
    {
        Srno: "7",
        Name: "Devansh Parman",
        Address: "Bodakdev, Ahmedabad",
        Phone: "7489657452",
        Email: "Raghav26897@Gmail.com",
        Booksfor: "Adult",
        BooksType: "Non-Fictional",
        Noofbooks:"4",
    },
    {
        Srno: "8",
        Name: "Zeel Chauhan",
        Address: "Ranip, Ahmedabad",
        Phone: "8965741256",
        Email: "Zeel7@Gmail.com",
        Booksfor: "Adult",
        BooksType: "Business, Economics",
        Noofbooks:"2",
    },
    {
        Srno: "9",
        Name: "Hemmu Verma",
        Address: "University, Ahmedabad",
        Phone: "8745693547",
        Email: "Hemmu@Gmail.com",
        Booksfor: "Kids",
        BooksType: "Action",
        Noofbooks:"5",
    },
    {
        Srno: "10",
        Name: "Abhishek Simp",
        Address: "Bapunagar, Ahmedabad",
        Phone: "8965745126",
        Email: "Abhishek@Gmail.com",
        Booksfor: "Adult",
        BooksType: "Academics",
        Noofbooks:"10",
    },
];

export default Rdata;